export default {
  'font.h1-size': '26px',
  'font.h1-weight': '600',
  'font.h2-size': '22px',
  'font.h2-weight': '600',
  'font.h3-size': '18px',
  'font.h3-weight': '600',
  'font.h4-size': '16px',
  'font.h4-weight': '600',
  'font.h5-size': '14px',
  'font.h5-weight': '600',
  'font.h5-size': '12px',
  'font.h5-weight': '600',
  'font.b-size': '13px',
  'base.line-height': '1.4em',
  'base.font-family': '-apple-system,BlinkMacSystemFont,sans-serif',
  'widget.border': 'white 1px solid',
  hoverBackground: '#2a2d2e', //not sure whats the base version of this
  'button.background': '#0e639c',
  'button.secondaryBackground': '#3a3d41',
  'button.foreground': 'white', //need to figure out how to do AND OR Things i think cannot do it in css3 but ye
  focusBorder: '1px solid #007fd4',
  foreground: '#cccccc',
  background: '#252526',
  'selection.background': '#007fd4',
  descriptionForeground: '#cccccc',
  'input.background': '#333333',
  'input.foreground': '#cccccd',
  'widget.shadow': 'rgba(0, 0, 0, 0.36) 0px 0px 8px 2px',
  'sash.hoverBorder': '#007fd4',
};
